name: personal_info_manager
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1
  sqflite: 1.1.2
  path_provider: 0.5.0+1
  flutter_slidable: 0.4.9
  intl: 0.15.7
  image_picker: 0.4.12+1
  flutter_calendar_carousel: ^1.4.9
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
